language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.0.26'
  - '7.0.27'
  - '7.0.28'
  - '7.0.29'
  - '7.0.30'
  - '7.1.12'
  - '7.1.13'
  - '7.1.14'
  - '7.1.15'
  - '7.1.16'
  - '7.1.17'
  - '7.1.18'
  - '7.1.9'
  - '7.2.0'
  - '7.2.1'
  - '7.2.2'
  - '7.2.3'
  - '7.2.4'
  - '7.2.5'
  - '7.2.6'
  - '7.2.7'
  - nightly

install: composer install

script: phpunit tests/SlugifyTest.php
